apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: guillermogomez
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
